name: Cyrpess Tests

on: [push, repository_dispatch]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup client
        run:  cd client && npm install && npm run build:css && npm run build
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npx serve -l 3000 -s ./client/build
          wait-on: 'http://localhost:3000'
